# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190819_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='hash',
            new_name='pw_hash',
        ),
    ]
