# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20190819_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
