# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_users_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthdate',
        ),
    ]
