# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-20 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_remove_users_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
