# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
